const Images = {
  IC_EMAIL: require('../asset/icon/ic_email.png'),
  IC_PASSWORD: require('../asset/icon/ic_password.png'),
  IC_USER: require('../asset/icon/ic_user.png'),
  IC_SEARCH: require('../asset/icon/ic_search.png'),
  IC_WISHLIST: require('../asset/icon/ic_wishlist.png'),
  IC_CART: require('../asset/icon/ic_cart.png'),
  IC_CART_ACTIVE: require('../asset/icon/ic_cart_active.png'),
  IC_HOME: require('../asset/icon/ic_home.png'),
  IC_HOME_ACTIVE: require('../asset/icon/ic_home_active.png'),
  IC_USER_ACTIVE: require('../asset/icon/ic_user_active.png'),
  IC_WISHLIST_ACTIVE: require('../asset/icon/ic_wishlist_active.png'),
  IC_ARROW_LEFT: require('../asset/icon/ic_arrow_left.png'),
  IC_ARROW_RIGHT: require('../asset/icon/ic_arrow_right.png'),
  IC_REMOVE: require('../asset/icon/ic_remove.png'),
  IC_EMPTY: require('../asset/icon/ic_empty.png'),
  IC_ADDRESS: require('../asset/icon/ic_address.png'),
  IC_EDIT_PROFILE: require('../asset/icon/ic_edit_profile.png'),
  IC_BACK: require('../asset/icon/ic_back.png'),
  IC_ADD: require('../asset/icon/ic_add.png'),
  IC_PHONE: require('../asset/icon/ic_phone.png'),
  IC_CITY: require('../asset/icon/ic_city.png'),
  IC_COMPANY: require('../asset/icon/ic_company.png'),
  IC_ZIPCODE: require('../asset/icon/ic_zipcode.png'),
  IC_DONE: require('../asset/icon/ic_check.png'),
  IC_DELETE: require('../asset/icon/ic_delete.png'),
  IC_TOP: require('../asset/icon/ic_top.png'),
  IC_X: require('../asset/icon/ic_x.png'),

  SplashImage: require('../asset/img/splash.png'),
  Logo: require('../asset/img/bg_shophouse.png'),
  BackgroundImage: require('../asset/img/splash_ui.png'),
  LoginBackground: require('../asset/img/login.png'),
  SignUpBackground: require('../asset/img/signup.png'),
};

export default Images;
